databases:
  - name: CSE 340 
    databaseName: dbname_4v5e
    user: dnameee

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: standard
   repo: https://github.com/Antoni1830/cse340-web-backend-dev-main.git
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: CSE 340 
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50